# fly.toml file

app = "ppalist"  # 填入创建应用的名字
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]


[[mounts]]
  destination = "/opt/alist/data"
  source = "data"

[[services]]
  http_checks = []
  internal_port = 5244
  #processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 50
    soft_limit = 35
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "120s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
