name: Fly Deploy cd
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 8 18 * *'  # 每月十八号八点（UTC）自动部署
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_NAME: ${{ secrets.APP_NAME }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: | 
           sh ./deploy.sh
